apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: personopplysninger-proxy
  namespace: min-side
  labels:
    team: min-side
spec:
  envFrom:
    - secret: personopplysninger-proxy-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /personopplysninger-proxy/internal/isAlive
    initialDelay: 10
  readiness:
    path: /personopplysninger-proxy/internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  ingresses:
    - "https://personopplysninger-proxy.prod-fss-pub.nais.io"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
