apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: personopplysninger-proxy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  replicas:
    min: 2
    max: 4
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: medlemskap-medl-api
        namespace: team-rocket
      - application: tps-proxy
        namespace: team-rocket
    inbound:
      rules:
        - application: dsop-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
        - application: arbeidsforhold-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
        - application: personopplysninger-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 384Mi
