apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: personopplysninger-proxy
  namespace: personbruker
  labels:
    team: personbruker
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  replicas:
    min: {{ min-replicas }}
    max: {{ max-replicas }}
  webproxy: true
  tokenx:
    enabled: true
  accessPolicy:
    rules:
      - application: medlemskap-medl-api
        namespace: team-rocket
      - application: {{ tps-proxy-appname }}
        namespace: team-rocket
      - application: {{ inst2-appname }}
        namespace: team-rocket
    inbound:
      rules:
        - application: dsop-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
        - application: arbeidsforhold-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
        - application: personopplysninger-api
          namespace: personbruker
          cluster: {{ gcp-cluster }}
  ingresses:
  {{#each ingresses}}
    - "{{this}}"
  {{/each}}
  vault:
    enabled: true
  resources:
    limits:
      cpu: 300m
      memory: 768Mi
    requests:
      cpu: 100m
      memory: 384Mi
