name: Build and deploy
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER:
        required: true

jobs:
  deploy:
    name: Build image and deploy to nais
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build application
        run: |
          ./gradlew clean build
      - name: Build and push docker image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: personbruker
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
      - name: Deploy to nais
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: ${{ inputs.environment }}-fss
          RESOURCE: ./nais/nais.yaml
          VAR: image=${{steps.docker-build-push.outputs.image}}
          VARS: ./nais/${{ inputs.environment }}-fss/personbruker.json

