name: Deploy to prod
on:
  release:
    types: [released]

jobs:
  deploy:
    if: github.event.release.target_commitish == 'main'
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: prod
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
