name: Deploy to dev
on:
  workflow_dispatch

jobs:
  deploy:
    permissions:
      contents: "read"
      id-token: "write"
    uses: ./.github/workflows/build-and-deploy.yml
    with:
      environment: dev
    secrets:
      NAIS_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
      NAIS_DEPLOY_APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
