name: Test and build branch
on:
  push

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: '~/.gradle/caches
        ~/.gradle/wrapper'
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}
      - name: Build application
        run: |
          ./gradlew clean build