name: Test and build branch
on:
  push

jobs:
  build-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut koden
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build application
        run: |
          ./gradlew clean build